'use client';

import { Calendar, Download, Eye, Trash2, FileText, FileJson, FileSpreadsheet, FilePdf } from 'lucide-react';

export default function ReportCard({ report, onView, onDownload, onDelete }) {
  const getFormatIcon = (format) => {
    switch (format) {
      case 'json':
        return <FileJson className="w-4 h-4 text-blue-500" />;
      case 'excel':
        return <FileSpreadsheet className="w-4 h-4 text-green-500" />;
      case 'pdf':
        return <FilePdf className="w-4 h-4 text-red-500" />;
      default:
        return <FileText className="w-4 h-4 text-gray-500" />;
    }
  };

  const getTypeLabel = (type) => {
    const labels = {
      activity_log: 'Activity Log',
      request_summary: 'Request Summary',
      trip_summary: 'Trip Summary',
      vehicle_utilization: 'Vehicle Utilization',
      driver_performance: 'Driver Performance',
      maintenance_report: 'Maintenance Report'
    };
    return labels[type] || type;
  };

  return (
    <div className="bg-white rounded-lg shadow hover:shadow-md transition-shadow">
      <div className="p-6">
        {/* Header */}
        <div className="flex items-start justify-between mb-4">
          <div className="flex items-center">
            {getFormatIcon(report.format)}
            <span className="ml-2 text-xs text-gray-500 uppercase">
              {report.format}
            </span>
          </div>
          <span className="px-2 py-1 bg-blue-100 text-blue-800 text-xs rounded-full">
            {getTypeLabel(report.type)}
          </span>
        </div>

        {/* Title */}
        <h3 className="font-medium text-gray-900 mb-2 line-clamp-2">
          {report.title}
        </h3>

        {/* Metadata */}
        <div className="space-y-2 mb-4 text-sm text-gray-600">
          <div className="flex items-center">
            <Calendar className="w-4 h-4 text-gray-400 mr-2" />
            {new Date(report.generatedAt).toLocaleDateString()}
          </div>
          <div className="flex items-center">
            <FileText className="w-4 h-4 text-gray-400 mr-2" />
            Generated by {report.generatedBy?.name || 'System'}
          </div>
        </div>

        {/* Summary Stats */}
        {report.summary && (
          <div className="grid grid-cols-2 gap-2 mb-4 p-3 bg-gray-50 rounded-lg">
            {Object.entries(report.summary).slice(0, 4).map(([key, value]) => (
              <div key={key}>
                <p className="text-xs text-gray-500">{key.replace(/([A-Z])/g, ' $1').trim()}</p>
                <p className="text-sm font-medium">{typeof value === 'number' ? value.toLocaleString() : value}</p>
              </div>
            ))}
          </div>
        )}

        {/* Actions */}
        <div className="flex items-center justify-end space-x-2 pt-4 border-t">
          <button
            onClick={onView}
            className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg"
            title="View Report"
          >
            <Eye className="w-5 h-5" />
          </button>
          <button
            onClick={onDownload}
            className="p-2 text-green-600 hover:bg-green-50 rounded-lg"
            title="Download"
          >
            <Download className="w-5 h-5" />
          </button>
          <button
            onClick={onDelete}
            className="p-2 text-red-600 hover:bg-red-50 rounded-lg"
            title="Delete"
          >
            <Trash2 className="w-5 h-5" />
          </button>
        </div>
      </div>
    </div>
  );
}