'use client';

import { X, Download, Calendar, User, FileText } from 'lucide-react';

export default function ViewReportModal({ report, onClose, onDownload }) {
  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg w-full max-w-4xl max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b sticky top-0 bg-white">
          <div>
            <h2 className="text-xl font-bold">{report.title}</h2>
            <p className="text-sm text-gray-500">Report ID: {report.reportId}</p>
          </div>
          <div className="flex items-center space-x-2">
            <button
              onClick={onDownload}
              className="flex items-center px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
            >
              <Download className="w-4 h-4 mr-2" />
              Download
            </button>
            <button onClick={onClose} className="text-gray-500 hover:text-gray-700">
              <X className="w-6 h-6" />
            </button>
          </div>
        </div>

        {/* Report Metadata */}
        <div className="p-6 bg-gray-50 border-b">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div>
              <p className="text-xs text-gray-500">Type</p>
              <p className="font-medium capitalize">{report.type?.replace('_', ' ')}</p>
            </div>
            <div>
              <p className="text-xs text-gray-500">Format</p>
              <p className="font-medium uppercase">{report.format}</p>
            </div>
            <div>
              <p className="text-xs text-gray-500">Generated</p>
              <p className="font-medium">{new Date(report.generatedAt).toLocaleString()}</p>
            </div>
            <div>
              <p className="text-xs text-gray-500">Generated By</p>
              <p className="font-medium">{report.generatedBy?.name || 'System'}</p>
            </div>
          </div>
        </div>

        {/* Report Content */}
        <div className="p-6">
          {report.summary && (
            <div className="mb-8">
              <h3 className="text-lg font-semibold mb-4">Summary</h3>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                {Object.entries(report.summary).slice(0, 4).map(([key, value]) => (
                  <div key={key} className="p-4 bg-blue-50 rounded-lg">
                    <p className="text-sm text-blue-600 capitalize">
                      {key.replace(/([A-Z])/g, ' $1').trim()}
                    </p>
                    <p className="text-2xl font-bold text-blue-800">
                      {typeof value === 'number' ? value.toLocaleString() : value}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Placeholder for detailed data */}
          <div className="text-center py-12 text-gray-500">
            <FileText className="w-16 h-16 text-gray-300 mx-auto mb-4" />
            <p>Detailed report data would be displayed here</p>
          </div>
        </div>
      </div>
    </div>
  );
}